### ISSUE TITLE
Definition Heckeoperatoren

### ISSUE THREAD

**Issue by ghost** [jenuk/modulformen#2]
Kapitel 2, Satz 2.7 ii)
Fehlt rechts der Faktor n^{k/2-1}, der beim konstanten Term und im Primfall erwähnt wird?

**Comment by ghost** [comment]
Bzw im Beweis wird das n mit in die Summe gezogen und ergibt als Normierung Sinn. :)
Stimmt dann mit den Beispielen etwas nicht?

**Comment by jenuk** [comment]
Der Faktor n^{k/2-1} ist überall falsch. Das ist uns neulich aufgefallen (der verschwindet ja auch am Ende vom Beweis), aber das hatte ich dann nicht vollständig korrigiert. Das er im konstanten Term noch zu viel stand, war mir schon aufgefallen, aber im Beispiel ist er natürlich auch zu viel.

Ich korrigier das gleich. Vielen Dank für den Hinweis!

**Comment by jenuk** [comment]
Also überall wenn wir die konkrete Form der Fourierreihe haben, in der Definition ist der Faktor richtig.
