### ISSUE TITLE
Minor typos

### ISSUE THREAD

**Issue by ghost** [jenuk/modulformen#3]
Kapitel 4.1.2: Zweite Formel: Bei g_n(m)= ... muss rechts im Nenner "4\pi n" statt "2 \pi n" stehen (nach eigenem Mitschrieb und vorhergehender und nachfolgender Formeln)

**Comment by ghost** [comment]
Kapitel 6, Bsp. 6.8. Im allgemeinen Fall ii) fehlt im Nenner der Exponent 's'

**Comment by ghost** [comment]
Bemerkung 6.5: ...stellt die Reihe [...] eine Funktion dar, die sIch auf eine Kreisscheibe...

**Comment by ghost** [comment]
Satz von Landau 6.6: KonvergenzabszissE

**Comment by ghost** [comment]
Bsp. 6.23: vervollsTändigte

**Comment by ghost** [comment]
Bsp. 6.23 Kuriose Anwendung: Die L*-Funktion hat 2*Pi statt s*Pi als Faktor

**Comment by ghost** [comment]
Heckescher Umkehrsatz 6.24: Sei L*(s)=[...] und L*(s) besitze_ eine hol. Fortsetzung...

**Comment by ghost** [comment]
Heckescher Umkehrsatz: In der Funktionalgleichung bei den Bedingungen ist L*(s) in den Exponenten gerutscht.

**Comment by dennis-grothe** [comment]
Heckescher Umkehrsatz: In der Funktionalgleichung bei den Bedingungen ist L*(s) in den Exponenten gerutscht.

**Comment by jenuk** [comment]
Das ist jetzt alles korrigiert. Wenn du mehr Fehler findest, sag Bescheid :)
siehe 8dc8130
